title: λ

months:
  - janvier
  - février
  - mars
  - avril
  - mai
  - juin
  - juillet
  - août
  - septembre
  - octobre
  - novembre
  - décembre

description: >-
  Cool articles on programming, design and lifestyle.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
