title: λ
url: https://rozaxe.github.io
author: rozaxe

months:
  - janvier
  - février
  - mars
  - avril
  - mai
  - juin
  - juillet
  - août
  - septembre
  - octobre
  - novembre
  - décembre

description: >-
  Cool articles on game programming, cooking and lifestyle !

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
